model_type: random_forest
n_estimators: 70
criterion: "mse"
max_depth: [10,14]
min_samples_split: 2
min_samples_leaf: 1
min_weight_fraction_leaf: 0.
max_features: 'log2'
max_leaf_nodes: [50,60,70]
min_impurity_decrease: 0.
min_impurity_split: ~
bootstrap: True
oob_score: False
n_jobs: ~
random_state: 233
verbose: 0
warm_start: False
ccp_alpha: 0.0
max_samples: ~

