# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(20, 20, 711, 521))
        self.tab.setObjectName("tab")
        self.prediction_train = QtWidgets.QWidget()
        self.prediction_train.setObjectName("prediction_train")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.prediction_train)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 180, 161, 104))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_dataset_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_dataset_btn.setObjectName("open_dataset_btn")
        self.verticalLayout.addWidget(self.open_dataset_btn)
        self.train_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.train_btn.setObjectName("train_btn")
        self.verticalLayout.addWidget(self.train_btn)
        self.progressBar = QtWidgets.QProgressBar(self.prediction_train)
        self.progressBar.setGeometry(QtCore.QRect(270, 430, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.prediction_train)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(470, 130, 160, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.algo_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.algo_select.setObjectName("algo_select")
        self.algo_select.addItem("")
        self.algo_select.addItem("")
        self.verticalLayout_3.addWidget(self.algo_select)
        self.prediction_config_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.prediction_config_btn.setObjectName("prediction_config_btn")
        self.verticalLayout_3.addWidget(self.prediction_config_btn)
        self.tab.addTab(self.prediction_train, "")
        self.prediction_infer = QtWidgets.QWidget()
        self.prediction_infer.setObjectName("prediction_infer")
        self.open_model_btn = QtWidgets.QPushButton(self.prediction_infer)
        self.open_model_btn.setGeometry(QtCore.QRect(180, 130, 159, 23))
        self.open_model_btn.setObjectName("open_model_btn")
        self.tab.addTab(self.prediction_infer, "")
        self.EA_train = QtWidgets.QWidget()
        self.EA_train.setObjectName("EA_train")
        self.tab.addTab(self.EA_train, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "综合实验平台"))
        self.open_dataset_btn.setText(_translate("MainWindow", "打开数据集"))
        self.train_btn.setText(_translate("MainWindow", "训练"))
        self.algo_select.setItemText(0, _translate("MainWindow", "lightgbm"))
        self.algo_select.setItemText(1, _translate("MainWindow", "随机森林"))
        self.prediction_config_btn.setText(_translate("MainWindow", "打开模型配置文件"))
        self.tab.setTabText(self.tab.indexOf(self.prediction_train), _translate("MainWindow", "预测模型训练"))
        self.open_model_btn.setText(_translate("MainWindow", "加载模型"))
        self.tab.setTabText(self.tab.indexOf(self.prediction_infer), _translate("MainWindow", "预测模型推理"))
        self.tab.setTabText(self.tab.indexOf(self.EA_train), _translate("MainWindow", "EA实验"))
